---
title: The Democratic Critiques and Populism
subtitle: GV482 Problem Set - Game Theory
date: last-modified
authors:
  - name: Dianyi Yang
execute:
  echo: false
  warning: false
  error: false
format:
  orcid-pdf:
    number-sections: false
    fig-pos: 'H'
---

# Part III - The Populist's entry decision (part of this will be solved on Thursday 2 February, the rest on Thursday 9 February) {#sec-part3}

In the previous part, we have computed the electoral decision of a voter from group $C$ as a function of her information. We use our previous answers to compute $P$'s electoral chances and entry decision under different scenarios.

## Q7

In this question, we suppose that mainstream candidates find it optimal to the commoners' preferred policy.

(a) Using your answers to **Q3**, explain briefly why $P$ never wins the election if he enters in this case.

    \color{blue}

    As we have shown in **Q3**, the probability of $P$ winning the election is $0$ if he enters.

    If $P$ proposes the same platform (commoners' preferred policy) as $A$ and $B$, $P$ will get no vote as both the commoners and elite will vote for the mainstream candidate with a positive valence shock. This corresponds to **Q3** (a).

    If $P$ proposes a different platform, and

    -   the commoners and the elite's preferred policy is the same, $P$ will get no vote as both the commoners and elite will vote for the mainstream candidate with a positive valence shock. This corresponds to **Q3** (b).

    -   the commoners and the elite's preferred policy is different, $P$ will only get the elite's votes. This accounts for $\sigma$ of the vote. Since this is less than 50%, $P$ will not win the election. This corresponds to **Q3** (c).

    \color{black}

(b) Explain why the populist never enters when $\sigma+(1+\sigma)(1−p)<\frac{1}{2}$.

    \color{blue}

    As we have shown in **Q2** (e), $\sigma+(1+\sigma)(1−p)<\frac{1}{2}$ implies that the mainstream candidates converge on the commoners preferred policy. As we discussed in Part (a), $P$ has no chance of winning in this case. As there is a cost to entry, $P$ will not enter:

    $$
    U_P(\text{enter})=-c<U_P(\text{not enter})=0
    $$

    \color{black}

## Q8

In question [Q8] and [Q9], we turn to the case when mainstream candidates converge to the elite citizens' preferred policy ($x_A = x_B = \omega_E$ and this is anticipated by commoners). In this question, we assume that $\alpha > 1/2$ and look at $P$'s entry decision then.

(a) Assume that mainstream candidates propose $x_A=x_B=0$ and the populist offers $x_P =1$. Assume further than the state is $\omega_C = 0$ (i.e., that is the optimal policy happens to be zero for the common voters). Using your answer to **Q5**(i), show that the vote share of candidate $P$ is: $(1 − \sigma)(1 − p)$. Explain why P does not win the election then.

    \color{blue}

    The elite know their preference well. They will vote for one of the maintream candidates and not populist $P$.

    As for the commoners,

    -   some receive signal of 1 ($s_{i,C}=1$). Their posterior belief (from **Q5** (j)) is:

        $$
        \mu(1,0,0,1)=\frac{(1-\alpha)p^2}{(1-\alpha)p^2+\alpha(1-p)^2}>\frac{1+|\delta|}{2}.
        $$

        They will vote for $P$.

    -   Some receive signal of 0 ($s_{i,C}=0$). Their posterior belief is:

        $$
        \mu(0,0,0,1)=1-\alpha
        $$

        Since we assume $\alpha>1/2$, $\mu(0,0,0,1)=1-\alpha<\frac{1}{2}<\frac{1=|\delta|}{2}$. They will not vote for $P$.

    Therefore, only the commoners who receive signal of 1 will vote for $P$. The probability of receiving this wrong signal $Pr(s_{i,C}=1\mid \omega_C=0)=1-p$. They therefore account for $(1-\sigma)(1-p)$ of total voters. Since $p>0.5$, this is smaller than 50%. Other voters will unite around the mainstream candidate with a positive valence shock, who will receive more than 50% of the vote. Therefore, $P$ will not win the election.

    \color{black}

(b) Assume that mainstream candidates propose $x_A=x_B=0$ and the populist offers $x_P =1$. Assume further than the state is $\omega_C = 1$ (i.e., that is the optimal policy happens to be one for the common voters). Show that the vote share of candidate P is: $(1 − \sigma)p$. Explain why $P$ loses the election then.

    \color{blue}

    The elite know their preference well. They will vote for one of the maintream candidates and not populist $P$.

    As for the commoners,

    -   some receive signal of 1 ($s_{i,C}=1$). Their posterior belief (from **Q5** (j)) is:

        $$
        \mu(1,0,0,1)=\frac{(1-\alpha)p^2}{(1-\alpha)p^2+\alpha(1-p)^2}>\frac{1+|\delta|}{2}.
        $$

        They will vote for $P$.

    -   Some receive signal of 0 ($s_{i,C}=0$). Their posterior belief is:

        $$
        \mu(0,0,0,1)=1-\alpha
        $$

        Since we assume $\alpha>1/2$, $\mu(0,0,0,1)=1-\alpha<\frac{1}{2}<\frac{1+|\delta|}{2}$. They will not vote for $P$.

    Therefore, only the commoners who receive signal of 1 will vote for $P$. The probability of receiving this right signal $Pr(s_{i,C}=1\mid \omega_C=1)=p$. They therefore account for $(1-\sigma)p$ of total voters. For the mainstream candidates to converge on the elite's preference, it requires:

    ```{=tex}
    \begin{align*}
    \sigma+(1-\sigma)(1-p)&\geq\frac{1}{2} \\
    \sigma+(1-\sigma)-(1-\sigma)p&\geq\frac{1}{2} \\
    (1-\sigma)p&\leq\frac{1}{2}
    \end{align*}
    ```
    Therefore, $P$ only receives less than half of the votes, whereas the mainstream candidate with a positive valence shock gathers more than half of the votes. $P$ therefore loses.

    \color{black}

(c) Assume that mainstream candidates propose $x_A = x_B = 1$ and the populist offers $x_P = 0$. Explain why P never wins the election.

    \color{blue}

    The elite know their preference well. They will vote for one of the maintream candidates and not populist $P$.

    As for the commoners,

    -   some receive signal of 1 ($s_{i,C}=1$). Their posterior belief (from **Q6** (a)) is:

        $$
        \mu(1,1,1,0)=\alpha.
        $$

        As we have shown in **Q6** (d), commoners with signal 1 in this case only vote for $P$ if and only if $\alpha<1/2$. As we assume $\alpha>1/2$ in this question, they will not vote for $P$.

    -   Some receive signal of 0 ($s_{i,C}=0$). Their posterior belief is:

        $$
        \mu(0,1,1,0)=\frac{(1-p)^2\alpha}{(1-p)^2\alpha+p^2(1-\alpha)}
        $$

        As we have shown in **Q6** (d), commoners with signal 0 in this case always vote for $P$.

    Therefore, only commoners with signal 0 will vote for $P$. The probability of receiving this signal is either $p$ or $1-p$. They therefore account for $(1-\sigma)p$ or $(1-\sigma)(1-p)$ of total voters. As we explored in Part (c), neither is greater than 50% and one of the mainstream candidates gathers the majority of the vote. Therefore, $P$ will not win the election.

    \color{black}

(d) Explain briefly why P never enters.

    \color{blue}

    We have shown that, when $\alpha>1/2$, the populist candidate $P$ never wins the election. No matter which policy the mainstream candidates converge on and what policy the populist candidate $P$ proposes, she has no chance of winning. Since there is a cost of running for election, $P$ will never enter the election.

    \color{black}

## Q9

We now look at $P$'s electoral chances and entry decision when $\alpha<1/2$.

(a) Assume that mainstream candidates propose $x_A=x_B=0$ and the populist offers $x_P=1$. Using your answer to **Q5**(i), show that the vote share of candidate $P$ is: ($1 − \sigma$). Explain why $P$ wins the election then.

    \color{blue}

    The elite will also vote for the mainstream candidates as their platform aligns with the elite's preference.

    As for the commoners,

    -   some receive signal of 1 ($s_{i,C}=1$). Their posterior belief (from **Q5** (j)) is:

        $$
        \mu(1,0,0,1)=\frac{(1-\alpha)p^2}{(1-\alpha)p^2+\alpha(1-p)^2}>\frac{1+|\delta|}{2}.
        $$

        They will vote for $P$.

    -   Some receive signal of 0 ($s_{i,C}=0$). Their posterior belief is:

        $$
        \mu(0,0,0,1)=1-\alpha
        $$

        Since we assume $\alpha<1/2$, $\mu(0,0,0,1)=1-\alpha>\frac{1+|\delta|}{2}$. This is shown in **Q5** (j). They will also vote for $P$.

    Therefore, the $P$ will enjoy all the votes, and only the votes of the commoners, who account for ($1-\sigma$) of all voters. Since there are more commoners than elite $1-\sigma>1/2$, $P$ will win the election.

    \color{black}

(b) Assume that mainstream candidates propose $x_A=x_B=1$ and the populist offers $x_P=0$. Explain why $P$ always wins the election then.

    \color{blue}

    The elite will also vote for the mainstream candidates as their platform aligns with the elite's preference.

    As for the commoners,

    -   some receive signal of 1 ($s_{i,C}=1$). Their posterior belief (from **Q6** (a)) is:

        $$
        \mu(1,1,1,0)=\alpha.
        $$

        As we have shown in **Q6** (d), $\mu(1,1,1,0)=\alpha<\frac{1-|\delta|}{2}$ when $\alpha<1/2$ and these commoners with signal of 1 will vote for $P$.

    -   some receive signal of 0 ($s_{i,C}=0$). Their posterior belief is:

        $$
        \mu(0,1,1,0)=\frac{(1-p)^2\alpha}{(1-p)^2\alpha+p^2(1-\alpha)}
        $$

        We have shown in **Q6** (d) it is true that $\mu(0,1,1,0)<\frac{1-|\delta|}{2}$ for all values of $\alpha$. Therefore these commoners with signal of 1 will also vote for $P$.

    Therefore, the $P$ will enjoy all the votes, and only the votes of the commoners, who account for ($1-\sigma$) of all voters. Since there are more commoners than elite $1-\sigma>1/2$, $P$ will win the election.

We now need to compute $P$'s expected payoff if $P$ enters. We consider the populist's entry decision so we no longer assume that $x_P = s_{P,C}$ (this has to be a choice of the populist). However, we still assume below that citizens anticipate that $x_P = s_{P,C}$ if the populist enters (we will see that this anticipation is correct below). In turn, both the citizens and the populist anticipate that the mainstream candidates propose $x_A=x_B=\omega_E$ (again, we will see that this anticipation is correct in [Part IV](#sec-part4).

To calculate $P$'s expected utility when he enters, we make use of $\rho(s_{P,C}, x_A, x_B)$ the populist's posterior that $\omega_C = 1$ given his signal and the mainstream candidates' platform choices.

(c) Show that the expected payoff of the populist candidate if he enters the race is:
    -   $0 − c$ if $x_P = x_A = x_B$

        \color{blue}

        As we have shown previously, $P$ never wins the election if he enters with the same platform as the mainstream candidates, as voters will vote for the mainstream candidate with a positive valence shock.

        In this case, the populist gets 0 from losing an election and $-c$ from entering the race, hence $U_P(x_A=x_B)=0-c$.

        \color{black}

    -   $\rho(s_{P,C}, 0, 0) − c$ if $x_P = 1$ and $x_A = x_B = 0$

        \color{blue}

        When $x_A=x_B=0$, the posterior belief is $Pr(\omega_C=1\mid s_{P,C}, x_A=0, x_B=0)=\rho(s_{P,C},0,0)$.

        If she proposes $x_P=1$, all common voters will vote for her as $\alpha<1/2$. This is shown in **Q5** (j). This means she will certainly win.

        Nevertheless, other than winning, $P$ also cares about implementing the right policy for the people. The probability that she proposes the right policy ($x_P=\omega_C=1$) is $\rho(S_{P,C},0,0)$. Hence her expected payoff:

        $$
        =Pr(\text{right policy and win})\times1 -c=\rho(s_{P,C},0,0)-c.
        $$

        \color{black}

    -   $1 − \rho(s_{P,C}, 1, 1) − c$ if $x_P = 0$ and $x_A = x_B = 1$

        \color{blue}

        When $x_A=x_B=1$, the posterior belief is $Pr(\omega_C=1\mid s_{P,C}, x_A=1, x_B=1)=\rho(s_{P,C},1,1)$.

        If she proposes $x_P=0$, all common voters will vote for her as $\alpha<1/2$. This is shown in **Q6** (d). This means she will certainly win.

        Nevertheless, other than winning, $P$ also cares about implementing the right policy for the people. The probability that she proposes the right policy ($x_P=\omega_C=0$) is $1-\rho(S_{P,C},1,1)$. Hence her expected payoff:

        $$
        =Pr(\text{right policy and win})\times1 -c=1-\rho(s_{P,C},1,1)-c.
        $$

        \color{black}

Obviously, $P$ does not enter at the same platform as the mainstream candidates. To see, whether $P$ enters at a different platform, we need to compute $P$'s posterior (belief) that the correct policy for group $C$ is $x = 1$ after observing his own signal $s_{P,C}$ and the other candidates' platforms $x_A$ and $x_B$. Recall as well that we still assume that mainstream candidates' platform is the optimal policy for the elite.

By Bayes' rule,

$$
\rho(s_{P,C},x_A,x_B)=\frac{Pr(s_{P,C},x_A,x_B\mid\omega_C=1)Pr(\omega_C=1)}{Pr(s_{P,C},x_A,x_B\mid\omega_C=1)Pr(\omega_C=1)+Pr(s_{P,C},x_A,x_B\mid\omega_C=0)Pr(\omega_C=0)}
$$ We again take these terms in turn.

(d) Suppose that $x_A = x_B = 0$ (at this point, it should be clear, I hope, that this means that the mainstream candidates propose policy 0). Explain briefly why $Pr(s_{P,C},x_A=0,x_B=0\mid\omega_C=1)=Pr(s_{P,C},\omega_E=0\mid\omega_C=1)$.

    \color{blue}

    This is because we assume in this question that the mainstream candidates converge to the elite's preference.

    \color{black}

(e) Suppose that $x_A = x_B = 0$. Explain why we can write: $$
    Pr(s_{P,C}, \omega_{E} = 0\mid\omega_{C} = 1) = Pr(s_{P,C}\mid\omega_C = 1)Pr(\omega_E = 0\mid\omega_C = 1)
    $$

    \color{blue}

    This is because, conditional on $\omega_C=1$, $s_{P,C}$ and $\omega_E$ are independent (not correlated). The former and latter are only correlated with $\omega_C$ and not with each other.

    \color{black}

(f) Suppose that $x_A = x_B = 0$. Show that

    1.  $Pr(s_{P,C}, \omega_E = 0\mid\omega_C = 1) = Pr(s_{P,C}\mid\omega_C = 1)(1 − \alpha)$

        \color{blue}

        ```{=tex}
        \begin{align*}
        =&Pr(s_{P,C}\mid\omega_C=1)Pr(\omega_E=0\mid\omega_C=1) \\
        =&Pr(s_{P,C}\mid\omega_C=1)(1-\alpha)
        \end{align*}
        ```
        \color{black}

    2.  $Pr(s_{P,C}, \omega_E = 0\mid\omega_C = 0) =Pr(s_{P,C}\mid\omega_C = 1)\alpha$

        \color{blue}

        ```{=tex}
        \begin{align*}
        =&Pr(s_{P,C}\mid\omega_C=0)Pr(\omega_E=0\mid\omega_C=0) \\
        =&Pr(s_{P,C}\mid\omega_C=0)\alpha
        \end{align*}
        ```
        \color{black}

    3.  $\rho(s_{P,C},x_A=0,x_B=0)=\frac{Pr(s_{P,C}\mid\omega_C=1)(1−\alpha)}{Pr(s_{P,C}\mid\omega_C=1)(1−\alpha)+Pr(s_{P,C}\mid\omega_C = 0)\alpha}$

        \color{blue}

        ```{=tex}
        \begin{align*}
        =&Pr(\omega_C=1\mid s_{P,C},x_A=0,x_B=0) \\
        =&\frac{Pr(s_{P,C},x_A=0,x_B=0\mid\omega_C=1)Pr(\omega_C=1)}{Pr(s_{P,C},x_A=0,x_B=0\mid\omega_C=1)Pr(\omega_C=1)+Pr(s_{P,C},x_A=0,x_B=0\mid\omega_C=0)Pr(\omega_C=0)}\\
        =&\frac{Pr(s_{P,C},\omega_E=0\mid\omega_C=1)}{Pr(s_{P,C},\omega_E=0\mid\omega_C=1)+Pr(s_{P,C},\omega_E=0\mid\omega_C=0)}\\
        =&\frac{Pr(s_{P,C}\mid\omega_C=1)Pr(\omega_E=0\mid\omega_C=1)}{Pr(s_{P,C}\mid\omega_C=1)Pr(\omega_E=0\mid\omega_C=1)+Pr(s_{P,C}\mid\omega_C=0)Pr(\omega_E=0\mid\omega_C=0)}\\
        =&\frac{Pr(s_{P,C}\mid\omega_C=1)(1-\alpha)}{Pr(s_{P,C}\mid\omega_C=1)(1-\alpha)+Pr(s_{P,C}\mid\omega_C=0)\alpha}
        \end{align*}
        ```
        \color{black}

(g) Using the previous result, show that $$
    \rho(s_{P,C} = 1, x_A = 0, x_B = 0)=\frac{p(1-\alpha)}{p(1-\alpha)+(1-p)\alpha}
    $$

    \color{blue}

    ```{=tex}
    \begin{align*}
    &\rho(s_{P,C} = 1, x_A = 0, x_B = 0) \\
    =&\frac{Pr(s_{P,C}=1\mid\omega_C=1)(1−\alpha)}{Pr(s_{P,C}=1\mid\omega_C=1)(1−\alpha)+Pr(s_{P,C}=1\mid\omega_C = 0)\alpha} \\
    =&\frac{p(1−\alpha)}{p(1−\alpha)+(1-p)\alpha}
    \end{align*}
    ```
    \color{black}

    $$
    \rho(s_{P,C} = 0, x_A = 0, x_B = 0)=\frac{(1-p)(1-\alpha)}{(1-p)(1-\alpha)+p\alpha}
    $$

    \color{blue}

    ```{=tex}
    \begin{align*} &\rho(s_{P,C} = 0, x_A = 0, x_B = 0) \\ =&\frac{Pr(s_{P,C}=0\mid\omega_C=1)(1−\alpha)}{Pr(s_{P,C}=0\mid\omega_C=1)(1−\alpha)+Pr(s_{P,C}=0\mid\omega_C = 0)\alpha} \\ =&\frac{(1-p)(1-\alpha)}{(1-p)(1-\alpha)+p\alpha} 
    \end{align*}
    ```
    \color{black}

(h) Suppose now that $x_A = x_B = 1$. Show that $$
    \rho(s_{P,C} = 1, x_A = 1, x_B = 1)=\frac{p\alpha}{p\alpha+(1-p)(1-\alpha)}
    $$

    \color{blue}

    ```{=tex}
    \begin{align*}
    &\rho(s_{P,C} = 1, x_A = 1, x_B = 1) \\
    =&\frac{Pr(s_{P,C}=1\mid\omega_C=1)\alpha}{Pr(s_{P,C}=1\mid\omega_C=1)\alpha+Pr(s_{P,C}=1\mid\omega_C = 0)(1-\alpha)} \\
    =&\frac{p\alpha}{p\alpha+(1-p)(1-\alpha)}
    \end{align*}
    ```
    \color{black}

    $$
    \rho(s_{P,C} = 0, x_A = 1, x_B = 1)=\frac{(1-p)\alpha}{(1-p)\alpha+p(1-\alpha)}
    $$

    \color{blue}

    ```{=tex}
    \begin{align*} 
    &\rho(s_{P,C} = 0, x_A = 1, x_B = 1) \\ 
    =&\frac{Pr(s_{P,C}=0\mid\omega_C=1)\alpha}{Pr(s_{P,C}=0\mid\omega_C=1)\alpha+Pr(s_{P,C}=0\mid\omega_C = 0)(1-\alpha)} \\ 
    =&\frac{(1-p)\alpha}{(1-p)\alpha+p(1-\alpha)}
    \end{align*}
    ```
    \color{black}

Now that we know $P$'s belief about what the correct policy is, we can think about his entry decision.

(i) Recall that $1/2 < c < p$ and $1 − p < \alpha < p$. Show that when $x_A = x_B = 0$, the populist enters with platform $x_P = 1$ if and only if $s_{P,C} = 1$ and does not enter otherwise.

    \color{blue}

    We have shown that in this case the expected payoff of running for $P$ is:

    $$
    \rho(s_{P,C},0,0)-c.
    $$

    The two other options for $P$ are, entering with platform $x_P=0$, which gives expected payoff of

    $$
    1-\rho(s_{P,C},0,0)-c,
    $$

    and not running, which gives expected payoff of 0.

    When $s_{P,C}=1$,

    ```{=tex}
    \begin{align*}
    \text{For}~&U_P(x_P=1)>U_P(x_P=0) \\
    \text{We need}~&\frac{p(1-\alpha)}{p(1-\alpha)+(1-p)\alpha}-c>1-\frac{p(1-\alpha)}{p(1-\alpha)+(1-p)\alpha}-c \\
    \text{which means}~&p(1-\alpha)-(1-p)\alpha>0. \\
    \text{This holds as the expression}&>p(1-p)-(1-p)p \\
    &=0
    \end{align*}
    ```
    ```{=tex}
    \begin{align*}
    \text{For}~&U_P(x_P=1)>U_P(\text{}x_P=\phi)~\text{we need:} \\
    &\frac{p(1-\alpha)}{p(1-\alpha)+(1-p)\alpha}-c-0>0 \\
    &\frac{(p-pc)(1-\alpha)-c(1-p)\alpha}{p(1-\alpha)+(1-p)\alpha}>0 \\
    &(p-pc)(1-\alpha)-c(1-p)\alpha>0.\\
    \text{Since}~&\alpha<1/2,~1-\alpha>\alpha\text{, we only need to prove:}\\
    &p-pc-c(1-p)>0\text{. Given}\\
    >&c-c^2-c(1-c) \\
    >&c-c^2-c+c^2=0\\
    \end{align*}
    ```
    This must be true. Therefore, when $s_{P,C}=1$ , $P$ enters with platform $x_P=1$.

    When $s_{P,C}=0$,

    ```{=tex}
    \begin{align*}
    \text{For}~&U_P(x_P=1)>U_P(x_P=0) \\
    \text{We need}~&\frac{(1-p)(1-\alpha)}{(1-p)(1-\alpha)+p\alpha} -c>1-\frac{(1-p)(1-\alpha)}{(1-p)(1-\alpha)+p\alpha} -c \\
    \text{which means}~&(1-p)(1-\alpha)-p\alpha>0. \\
    \text{This does not hold as the expression}&<(1-p)p-p(1-p) \\
    &=0
    \end{align*}
    ```
    ```{=tex}
    \begin{align*}
    \text{For}~&U_P(x_P=1)>U_P(\text{}x_P=\phi)~\text{we need:} \\
    &\frac{(1-p)(1-\alpha)}{(1-p)(1-\alpha)+p\alpha} -c-0>0 \\
    &\frac{(1-p)(1-\alpha)-c(1-p)(1-\alpha)-cp\alpha}{(1-p)(1-\alpha)+p\alpha}>0 \\
    &(1-p)(1-\alpha)-c(1-p)(1-\alpha)-cp\alpha>0 \\
    &(1-c)(1-p)(1-\alpha)>cp\alpha. \\
    \text{This requires}~&(1-c)(1-p)p>cp(1-p).\\
    \text{This is no met as}~&c>1/2~\text{and}~1-c<c.
    \end{align*}
    ```
    Therefore, when $s_{P,C}=0$, entering with platform $x_P=1$ is dominated by the other two options and not chosen by $P$.

    Hence, when $x_A = x_B = 0$, the populist enters with platform $x_P = 1$ if and only if $s_{P,C} = 1$ and does not enter otherwise.

    \color{black}

By a similar reasoning as above, we can also show that when $x_A = x_B = 1$, the populist enters with platform $x_P = 0$ if and only if $s_{P,C} = 0$ and does not enter otherwise (you are encouraged to check this yourself). With this in mind, we turn to the mainstream parties' adaptation under the threat of populist entry.

# Part IV - The mainstream parties' adaptation {#sec-part4}

In this last part, we consider how the mainstream parties react to the populist’s threat of entry. As we have seen in [part III](#sec-part3), this threat materializes only if $\sigma+(1−\sigma)(1−p)>1/2$ and $\alpha < 1/2$ so we will assume this holds in what follows (in all other cases, it is business as normal for the mainstream candidates). Further, we assume that the populist and citizens anticipate that candidates play an elite-driven strategy ($x_A = x_B = \omega_E$). When they observe diverging platform, all citizens follow their signal as we assumed in **Part I**. In the questions that follow, we consider $A$’s incentive to deviate (keeping $B$’s behavior constant, $x_B = \omega_E$). We ask ourselves: what should $A$ do? Should he propose $x_A = \omega_E$ or should he deviate and go on proposing a different policy? We are going to answer these questions under different possible scenarios.

# Q10

We consider the following case: $\omega_E = 0$ so $B$ proposes policy $x_B = 0$, and $\omega_C = 0$ so the optimal policy for the common people is the same as for the elite.

(a) Suppose $A$ proposes $x_A = 1$. Show that the populist does not enter then.

    \color{blue}

    In this case, all of the elites vote for $B$ as they know their state well.

    However, as for the commoners, they no longer learn from the mainstream candidates' platforms as they do not know who is deviating. Here we assume $P$ proposes the same platform as her signal if she enters:

    $$
    Pr(\omega_C=1\mid s_{i,C}, x_A=1,x_B=0, x_P)=Pr(\omega_C=1\mid s_{i,C},s_{P,C})
    $$

    If the $P$ gets signal $s_{P,C}=0$ with probability $p$ and proposes $x_P=0$,

    -   For the commoners, their expected utility from voting for different candidates:

        ```{=tex}
        \begin{align*}
        U_{i,C}(A\mid s_{i,C}, s_{P,C}=0)&=Pr(\omega_C=1\mid s_{i,C}, s_{P,C}=0)+\delta \\
        U_{i,C}(B\mid s_{i,C}, s_{P,C}=0)&=1-Pr(\omega_C=1\mid s_{i,C}, s_{P,C}=0)-\delta \\
        U_{i,C}(P\mid s_{i,C}, s_{P,C}=0)&=Pr(\omega_C=1\mid s_{i,C}, s_{P,C}=0)
        \end{align*}
        ```
        For them to vote for $P$, it requires that $U_{i,C}(P\mid s_{i,C}, s_{P,C}=0)>U_{i,C}(A\mid s_{i,C}, s_{P,C}=0)$.

        This requires $\delta>0$, which is true with probability $1/2$.

        This means $P$ wins with probability $1/2$ *at most*.

        Even if $P$ gets the right signal (which maximises her payoff), her utility from running is *at most*

        $$
        U_P^{max}(x_P=0)=1/2-c<0=U_P(x_P=\phi)~\text{as c>1/2}
        $$

        This means the populist $P$ will not enter in this case.

    If the $P$ gets signal $s_{P,C}=1$ with probability $1-p$ and proposes $x_P=1$,

    -   For the commoners, their expected utility from voting for different candidates:

        ```{=tex}
        \begin{align*}
        U_{i,C}(A\mid s_{i,C}, s_{P,C}=1)&=Pr(\omega_C=1\mid s_{i,C}, s_{P,C}=1)+\delta \\
        U_{i,C}(B\mid s_{i,C}, s_{P,C}=1)&=1-Pr(\omega_C=1\mid s_{i,C}, s_{P,C}=1)-\delta \\
        U_{i,C}(P\mid s_{i,C}, s_{P,C}=1)&=Pr(\omega_C=1\mid s_{i,C}, s_{P,C}=1)
        \end{align*}
        ```
        For them to vote for $P$, it requires that $U_{i,C}(P\mid s_{i,C}, s_{P,C}=1)>U_{i,C}(A\mid s_{i,C}, s_{P,C}=1)$.

        This requires $\delta>0$, which is true with probability $1/2$.

        This means $P$ wins with probability $1/2$ *at most*.

        Even if $P$ gets the right signal (which maximises her payoff), her utility from running is *at most*

        $$
        U_P^{max}(x_P=1)=1/2-c<0=U_P(x_P=\phi)~\text{as c>1/2}
        $$

        This means the populist $P$ will not enter in this case.

    Therefore, if $A$ proposes $x_A = 1$. the populist $P$ does not enter then.

    \color{black}

(b) Suppose $A$ proposes $x_A = 1$. Show that $A$’s vote share is $(1 − \sigma)(1 − p)$. Explain briefly why $A$ does not win the election then.

    \color{blue}

    We now know that when $A$ deviates, $P$ does not enter. In this case, all of the elites (accounting for $\sigma$ of total voters) vote for $B$ as $x_P=\omega_E=0$.

    As for the commoners, the only information for them is their own signal as they cannot distinguish $A$ or $B$ deviates and they know that $P$ does not enter if either mainstream candidate deviates:

    $$
    \mu(s_{i,C},1,0,\phi)=Pr(\omega_C=1\mid s_{i,C})
    $$

    -   For those with the right signal $s_{i,C}=0$, who account for $p$ of common voters:

        $$
        \mu(0,1,0,\phi)=Pr(\omega_C=1\mid s_{i,C}=0)=1-p
        $$

        Their expected payoffs from voting for mainstream candidates:

        ```{=tex}
        \begin{align*}
        U_{i,C}(A\mid s_{i,C}=0)&=1-p+\delta \\
        U_{i,C}(B\mid s_{i,C}=0)&=p-\delta \\
        \end{align*}
        ```
        As shown in **Q2** (c), $\bar{\delta}<\max\{\frac{2\alpha-1}{2},\frac{1-2\alpha}{2}\}<\frac{2p-1}{2}$,

        ```{=tex}
        \begin{align*}
        &U_{i,C}(A\mid s_{i,C}=0)-U_{i,C}(B\mid s_{i,C}=0) \\
        =&(1-p+\delta)-(p-\delta) \\
        =&1-2p+2\delta \\
        <&1-2p+2\bar{\delta}\\
        =&1-2p+2\frac{2p-1}{2} \\
        =&0
        \end{align*}
        ```
        Therefore thosecommon voters with the right signal $s_{i,c}=0$ vote for $B$.

    -   For those with the wrong signal $s_{i,C}=1$, who account for $(1-p)$ of common voters and $(1-\sigma)(1-p)$ of total voters:

        $$
        \mu(1,1,0,\phi)=Pr(\omega_C=1\mid s_{i,C}=1)=p
        $$

        Their expected payoffs from voting for mainstream candidates:

        ```{=tex}
        \begin{align*} 
        U_{i,C}(A\mid s_{i,C}=1)&=p+\delta \\ 
        U_{i,C}(B\mid s_{i,C}=1)&=1-p-\delta \\ 
        \end{align*}
        ```
        As shown in **Q2** (c), $\bar{\delta}<\max\{\frac{2\alpha-1}{2},\frac{1-2\alpha}{2}\}<\frac{2p-1}{2}$,

        ```{=tex}
        \begin{align*}
        &U_{i,C}(A\mid s_{i,C}=1)-U_{i,C}(B\mid s_{i,C}=1) \\
        =&(p+\delta)-(1-p-\delta) \\
        =&2p-1+2\delta \\
        >&1+2p-2\bar{\delta}\\
        =&1+2p-2\frac{2p-1}{2} \\
        =&0
        \end{align*}
        ```
        Therefore those common voters with the wrong signal $s_{i,c}=1$ vote for $A$.

    Therefore, only those common voters with the wrong signal $s_{i,c}=1$ vote for $A$. They account for $(1-\sigma)(1-p)$ of total voters. Since $1-p<1/2$, $(1-\sigma)(1-p)<1/2$. As there are only two candidates, $A$ loses the election.

    \color{black}

(c) Suppose now that $x_A = 0$. Show that if $P$ enters at $x_P = 1$, then $A$ loses the election for sure.

    \color{blue}

    In this case, the elites will vote for one of the mainstream candidates with a positive valance shock:

    ```{=tex}
    \begin{align*}
    U_{i,E}(P)=0<U_{i,E}(A)=1+\delta \\
    U_{i,E}(P)=0<U_{i,E}(B)=1-\delta
    \end{align*}
    ```
    As for the commoners, they all voter for $P$ as $\alpha<1/2$. This is shown in **Q5** (j). As commoners outnumber the elites $(1-\sigma)>1/2$, the populist $P$ wins for sure and both $A$ and $B$ lose the election for sure.

    \color{black}

(d) Suppose now that $x_A = 0$. Explain carefully why $A$’s chance of winning the election is $\frac{p}{2}$.

    \color{blue}

    As previously shown in **Q9** (i), the populist enters with platform $x_P = 1$ if and only if $s_{P,C} = 1$ and does not enter otherwise and never proposes $x_P=0$ in this case (from **Q9** (c)).

    Therefore, the probability of $P$ proposing $x_P=1$ and winning the election is ($1-p$).

    When $P$ is not running in the election, with probability $p$, the expected payoff for the voters:

    ```{=tex}
    \begin{align*}
    U_{i,E}(A)&=1+\delta \\
    U_{i,E}(B)&=1-\delta \\
    U_{i,C}(A)&=1-\mu(s_{i,C},0,0,\phi)+\delta \\
    U_{i,C}(B)&=1-\mu(s_{i,C},0,0,\phi)-\delta
    \end{align*}
    ```
    In this case, the mainstream candidate with positive valence shock receives all of the votes and thus wins the election. Since the valence shock $\delta\in[-\bar{\delta},\bar{\delta}]$ is uniformly distributed, it has equal probabilities of being positive and negative. Hence both $A$ and $B$ have 1/2 chance of winning the election when $P$ is not running.

    Hence the $A$'s chance of winning is $[1-(1-p)]\times\frac{1}{2}=\frac{p}{2}$.

    \color{black}

(e) Explain why $A$ also has no incentive to deviate in this case (i.e., prefers to propose $x_A = 0$ over $x_A = 1$).

    \color{blue}

    As we have previously shown, when $A$ deviates, $P$ does not enter (a) and $A$ loses the election (b). In this case, her expected payoff:

    $$
    U_A(\text{deviate})=U_A(\text{lose})=0
    $$

    When $A$ does not deviate, she has $\frac{p}{2}$ chance of winning (from (d)). Her expected payoff:

    ```{=tex}
    \begin{align*}
    U_A(\text{not deviate})&=U_A(\text{win})\times\frac{p}{2}+U_A(\text{lose})\times(1-\frac{p}{2}) \\
    &=1\times\frac{p}{2}+0\times(1-\frac{p}{2}) \\
    &=\frac{p}{2}>0=U_A(\text{deviate})
    \end{align*}
    ```
    Therefore $A$ has no incentive to deviate.

    \color{black}

# Q11

We now turn to a different case with $\omega_E = 0$, so $B$ proposes policy $x_E = 0$, and $\omega_C = 1$ so the optimal policy for the common people is different than the optimal policy for the elite.

(a) Explain briefly why $A$’s vote share is $(1 − \sigma)p$ if he proposes $x_A = 1$.

    \color{blue}

    In a similar fashion to [Q10] (a), $P$ will not enter in this case:

    -   It is known that $P$ does not enter with $x_P=0$.

    -   the elites will not vote for $P$ if $x_P=1$.

    -   For the commoners, the expected payoffs of voting for different candidates:

        ```{=tex}
        \begin{align*}
        U_{i,C}(A\mid s_{i,C}, s_{P,C}=1)&=Pr(\omega_C=1\mid s_{i,C}, s_{P,C}=1)+\delta \\
        U_{i,C}(B\mid s_{i,C}, s_{P,C}=1)&=1-Pr(\omega_C=1\mid s_{i,C}, s_{P,C}=1)-\delta \\
        U_{i,C}(P\mid s_{i,C}, s_{P,C}=1)&=Pr(\omega_C=1\mid s_{i,C}, s_{P,C}=1)
        \end{align*}
        ```

    -   $P$ beats $A$ with probability $1/2$ *at most*.

    -   $P$ will not enter as there is cost of running $c$, let alone the possibility that she receives the wrong signal.

    Also in a similar fashion to [Q10] (b),

    -   All of the elites ($\sigma$) vote for $B$.

    -   Among the commoners ($1-\sigma$),

        -   Those with the right signal $s_{i,C}=1$ account for $(1-\sigma)p$ of total voters.

            Their belief:

            $$
            \mu(1,1,0,\phi)=Pr(\omega_C=1\mid s_{i,C}=1)=p
            $$

            Their expected payoffs from voting for the mainstream candidates:

            ```{=tex}
            \begin{align*}
            U_{i,C}(A\mid s_{i,C}=1)&=p+\delta \\
            U_{i,C}(B\mid s_{i,C}=1)&=1-p-\delta \\
            \end{align*}
            ```
            They will vote for $A$.

        -   Those with the wrong signal $s_{i,C}=0$ account for $(1-\sigma)(1-p)$ of total voters.

            Their belief:

            $$
            \mu(0,1,0,\phi)=Pr(\omega_C=1\mid s_{i,C}=0)=1-p
            $$

            Their expected payoffs from voting for the mainstream candidates:

            ```{=tex}
            \begin{align*}
            U_{i,C}(A\mid s_{i,C}=0)&=1-p+\delta \\
            U_{i,C}(B\mid s_{i,C}=0)&=p-\delta \\
            \end{align*}
            ```
            They will vote for $B$.

    -   Therefore only common voters with the correct signal will vote for $A$, Their share is $(1-\sigma)p$.

    \color{black}

(b) Suppose now that $x_A = 0$. Explain carefully why $A$’s chance of winning the election is $\frac{1−p}{2}$.

    \color{blue}

    As previously shown in **Q9** (i), the populist enters with platform $x_P = 1$ if and only if $s_{P,C} = 1$ and does not enter otherwise and never proposes $x_P=0$ in this case (from **Q9** (c)).

    Therefore, the probability of $P$ proposing $x_P=1$ and winning the election is ($p$).

    When $P$ is not running in the election, with probability $1-p$, the expected payoff for the voters:

    ```{=tex}
    \begin{align*}
    U_{i,E}(A)&=1+\delta \\
    U_{i,E}(B)&=1-\delta \\
    U_{i,C}(A)&=1-\mu(s_{i,C},0,0,\phi)+\delta \\
    U_{i,C}(B)&=1-\mu(s_{i,C},0,0,\phi)-\delta
    \end{align*}
    ```
    In this case, the mainstream candidate with positive valence shock receives all of the votes and thus wins the election. Since the valence shock $\delta\in[-\bar{\delta},\bar{\delta}]$ is uniformly distributed, it has equal probabilities of being positive and negative. Hence both $A$ and $B$ have 1/2 chance of winning the election when $P$ is not running.

    Hence the $A$'s chance of winning is $(1-p)\times\frac{1}{2}=\frac{1-p}{2}$.

    \color{black}

(c) Explain why $A$ also has no incentive to deviate in this case (i.e., prefers to propose $x_A = 0$ over $x_A = 1$).

    \color{blue}

    As we have previously shown, when $A$ deviates, $P$ does not enter (a) and $A$ receives $(1-\sigma)p$ of the votes. We know $(1-\sigma)p<1/2$ and hence $A$ loses the election to $P$ as under this setting, the mainstream candidates were supposed to converge on the elites' interest. This means, from **Q2** (e):

    ```{=tex}
    \begin{align*}
    \sigma+(1-\sigma)(1-p)&>\frac{1}{2} \\
    \sigma+1-\sigma-p+\sigma p &> \frac{1}{2} \\
    -p+\sigma p&>-\frac{1}{2} \\
    p-\sigma p &< \frac{1}{2} \\
    (1-\sigma)p&<\frac{1}{2}
    \end{align*}
    ```
    In this case, her expected payoff:

    $$
    U_A(\text{deviate})=U_A(\text{lose})=0
    $$

    When $A$ does not deviate, she has $\frac{1-p}{2}$ chance of winning (from (b)). Her expected payoff:

    ```{=tex}
    \begin{align*}
    U_A(\text{not deviate})&=U_A(\text{win})\times\frac{1-p}{2}+U_A(\text{lose})\times(1-\frac{1-p}{2}) \\
    &=1\times\frac{1-p}{2}+0\times(1-\frac{1-p}{2}) \\
    &=\frac{1-p}{2}>0=U_A(\text{deviate})
    \end{align*}
    ```
    Therefore $A$ has no incentive to deviate.

    \color{black}

Obviously, the same logic applies when $\omega_E = 1$. Further, since $A$ and $B$ face similar incentives, if $A$ has no incentive to deviate so does $B$.

# Q12

Given your answers above, can you provide some intuition why the two mainstream candidates do not react to the threat of entry of the populist candidate?

\color{blue}

Intuition: the mainstream candidates do not react to the threat of entry of the populist candidate because accommodating populist demands only drives away the populist candidate, but makes the deviating candidate lose to the elite-based counterpart, as the elites and (mis)informed commoners outnumber the rest.

However, if they did not cater to the populist demands, there is a chance of winning if the populist receives the same signal as their platform and does not enter the election.

\color{black}

Congratulations. We have finally shown that there is an equilibrium in which the mainstream candidates cater to the elite ($x_K = \omega_E$, $K\in\{A, B\}$), the populist enters when $s_{P,C} \neq x_K$ and wins the election then. Notice that the populist’s entry and success is, in this problem set, the result of a representation failure. This representation failure arises when two conditions are met:

1.  Large political inequality ($p$ is sufficiently low so $\sigma + (1 − \sigma)(1 − p) > (1 − \sigma)p$), which leads to an elite-driven equilibrium from mainstream parties.

2.  The interests of the elite and the commoners are misaligned ($\alpha < 1/2$), so that the populist can receive the vote of all commoners and has the electoral incentives to enter.

These are the themes we have been developing in the lectures.
